### PR TITLE
Upgrade helper

### PR DESCRIPTION
**Pull request by nicolaslara**
ref https://github.com/apppackio/apppack/issues/38

### CODE REVIEW

**Comment by ipmb** [comment]
looks like the tests are failing and there is some code cleanup that could be done [according to deepsource](https://deepsource.io/gh/apppackio/apppack/run/378d41f7-f5dc-48cc-b2e8-9a956cdf1fbc/go/)

**Comment by ipmb** [comment]
This looks good, but I'd like to avoid having it block every command before it runs for the check. Could we do what `gh` does and trigger the request in the background, then show the results after the command runs? https://github.com/cli/cli/blob/trunk/cmd/gh/main.go#L57-L61

**Comment by nicolaslara** [comment]
That makes sense. I figured the update was was enough that it wouldn't matter, but I'll update it

**Comment by ipmb** [comment]
Closing in favor of #47

**Pull request closed without merging**
